"""Init command: create project scaffold."""

import os
from argparse import Namespace
from pathlib import Path

from rich.console import Console
from rich.panel import Panel

console = Console()


class InitCommand:
    def __init__(self, args: Namespace):
        self.name = args.name
        self.path = Path(args.path) / args.name

    def execute(self):
        console.print(Panel(f"Initializing project: [bold]{self.name}[/bold]"))

        dirs = ["src", "tests", "docs", "config"]
        for d in dirs:
            (self.path / d).mkdir(parents=True, exist_ok=True)
            console.print(f"  [green]✓[/green] Created {d}/")

        (self.path / "src" / "__init__.py").touch()
        (self.path / "tests" / "__init__.py").touch()

        readme = f"# {self.name}\n\nGenerated by pytemplate-cli.\n"
        (self.path / "README.md").write_text(readme)

        console.print(f"\n[bold green]Project '{self.name}' ready at {self.path}[/bold green]")
